# Generated by Django 3.0.4 on 2021-03-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('category_img', models.ImageField(upload_to='catogory')),
            ],
        ),
        migrations.CreateModel(
            name='BooksInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_name', models.CharField(max_length=100)),
                ('books_author', models.CharField(max_length=50)),
                ('books_price', models.IntegerField(default=0)),
                ('books_description', models.CharField(max_length=2000)),
                ('books_img', models.ImageField(upload_to='books')),
                ('books_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BooksCategory')),
            ],
        ),
    ]
