# Generated by Django 3.0.13 on 2021-04-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksinfo',
            name='books_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
