# Generated by Django 3.0.4 on 2021-03-30 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('order_addr', models.CharField(max_length=100)),
                ('order_recv', models.CharField(max_length=50)),
                ('order_tele', models.CharField(max_length=10)),
                ('order_fee', models.IntegerField(default=10)),
                ('order_extra', models.CharField(max_length=200)),
                ('order_status', models.IntegerField(choices=[(1, 'to be paid'), (2, 'to be delivered'), (3, 'to be reveived'), (4, 'Finished')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_num', models.IntegerField()),
                ('books_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BooksInfo')),
                ('books_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.OrderInfo')),
            ],
        ),
    ]
