# Generated by Django 3.0.13 on 2021-04-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'to be paid'), (2, 'to be delivered'), (3, 'to be received'), (4, 'Finished')], default=1),
        ),
    ]
