# Generated by Django 3.0.13 on 2021-04-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='name',
        ),
    ]
